services:
  iz-seeder-bot:
    image: ivnjey/iz-seeder-bot:0.0.1
    container_name: iz-seeder-bot
    volumes:
      - ./config.json:/config.json
      - /tmp/iz-seeder-bot/upload:/tmp/iz-seeder-bot/upload
      - /tmp/iz-seeder-bot/transcoding:/tmp/iz-seeder-bot/transcoding
      - /var/tmp/iz-seeder-bot/seeding:/tmp/iz-seeder-bot/seeding
    restart: unless-stopped