services:
  iz-seeder-bot:
    build: .
    image: ivnjey/iz-seeder-bot:${VERSION}
    container_name: iz-seeder-bot
    volumes:
      - ./config.json:/app/config.json
      - /tmp/iz-seeder-bot:/tmp/iz-seeder-bot
      - /var/tmp/iz-seeder-bot:/var/tmp/iz-seeder-bot
    restart: unless-stopped