services:
  iz-seeder-bot:
    image: iz-seeder-bot
    build: .
    volumes:
      - ./config.json:/config.json
      - /tmp/iz-seeder-bot/upload:/tmp/iz-seeder-bot/upload
      - /tmp/iz-seeder-bot/transcoding:/tmp/iz-seeder-bot/upload
      - /var/tmp/iz-seeder-bot/seeding:/tmp/iz-seeder-bot/upload
    restart: unless-stopped